# Site
repository: AvinashChavanN/avinashchavann.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Avinash Chavan
title: Modern Front End Developer
email: chvn.avi@gmail.com
phone: +1 (682) 347 6514
website: https://github.com/avinashchavann

# Social links
github_username:  avinashchavann
linkedin_username: avinash-chavan

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Software engineering professional with more than 6 years of experience in object-oriented approaches to real-time software development that encompasses analysis, design, development, unit testing, integration testing, deployment and support. 

  Full stack development of web applications and creative cloud engineer.

  And yes I love to explore new libraries in <mark>JavaScript</mark>.
    
# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  -	<mark>Front-End:</mark> HTML5, CSS3, JavaScript, TypeScript, Angular, React, Redux, Flux, NodeJS, jQuery, AJAX
  -	<mark>Back-End:</mark> PHP MVC(CodeIgniter), ASP.NET C#, MVC, RESTful API, Web API, Authenticate.Net 
  -	<mark>Build Deploy and Version Control Tools:</mark> Git, Maven, Jenkins, Ant, IntelliJ, Sourcetree
  -	<mark>Programming Skills:</mark> Java, C#, PHP
  -	<mark>SQL Database:</mark> Oracle, MySQL, Postgres SQL, expert in stored procedures, cursors, triggers 
  -	<mark>NoSQL:</mark> mongoDB, Neo4j
  -	<mark>Cloud Platforms:</mark> AWS, GCP
# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

#Experience Section
experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)


# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
